#!ruby

platform :ios, '7.0'

#Before push use:
#pod "SHUImagePickerController"

#For local development use:
pod "SHUImagePickerController", :path => "../SHUImagePickerController.podspec"

link_with ['SHUImagePickerControllerExample', 'SHUImagePickerControllerExampleTests']
