#!ruby

platform :ios, '8.0'
use_frameworks!

#Before push use:
#pod "SHUImagePickerController"

#For local development use:
pod "SHUImagePickerController", :path => "../SHUImagePickerController.podspec"

link_with ['SHUImagePickerControllerExample', 'SHUImagePickerControllerExampleTests']
